version: '3.8' # docker-compose config version
volumes:
    wp: {}
    db: {}
services:
    wordpress:
        image: wordpress:5.5.1-php7.4
        volumes:
            - wp:/var/www/html
        depends_on:
            - database
        ports:
            - "81:80"
        restart: on-failure
        env_file:
            - ./credentials/dev.env
    database:
        image: mysql:5.7
        volumes:
            - db:/var/lib/mysql
        restart: on-failure
        env_file:
            - ./credentials/dev.env
