version: '3.3'
volumes:
    wp: {}
    db: {}
services:
    wordpress:
        image: wordpress:5.5.1-php7.4
        volumes:
            - wp:/var/www/html
        depends_on:
            - database
        ports:
            - "8000:80"
        restart: on-failure
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: jmarc
            WORDPRESS_DB_PASSWORD: publicpassword
            WORDPRESS_DB_NAME: wordpress
    database:
        image: mysql:5.7
        volumes:
            - db:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: secretpassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: jmarc
            MYSQL_PASSWORD: publicpassword
